source = open("german.data-numeric", "r")
dest = open("german_nume.arff", "w")
dest.write("@relation German\n") 
dest.write("@attribute Attribute1 REAL\n")  
dest.write("@attribute Attribute2 REAL\n")
dest.write("@attribute Attribute3 REAL\n")
dest.write("@attribute Attribute4 REAL\n")
dest.write("@attribute Attribute5 REAL\n")
dest.write("@attribute Attribute6 REAL\n")
dest.write("@attribute Attribute7 REAL\n")
dest.write("@attribute Attribute8 REAL\n")
dest.write("@attribute Attribute9 REAL\n")
dest.write("@attribute Attribute10 REAL\n")
dest.write("@attribute Attribute11 REAL\n")
dest.write("@attribute Attribute12 REAL\n")
dest.write("@attribute Attribute13 REAL\n")
dest.write("@attribute Attribute14 REAL\n")
dest.write("@attribute Attribute15 REAL\n")
dest.write("@attribute Attribute16 REAL\n")
dest.write("@attribute Attribute17 REAL\n")
dest.write("@attribute Attribute18 REAL\n")
dest.write("@attribute Attribute19 REAL\n")  
dest.write("@attribute Attribute20 REAL\n")
dest.write("@attribute Attribute21 REAL\n")
dest.write("@attribute Attribute22 REAL\n")
dest.write("@attribute Attribute23 REAL\n")
dest.write("@attribute Attribute24 REAL\n")
dest.write("@data\n")
for ligne in source:
    dest.write(ligne.replace("   ", ",").replace("  ", ",")[1:])
